Resources:
    ChatTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: chatId
                  AttributeType: S
                - AttributeName: chatSortKey
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: chatSortKeyIndex
                  KeySchema:
                      - AttributeName: chatSortKey
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: chatId
                  KeyType: HASH
                - AttributeName: chatSortKey
                  KeyType: RANGE
            TableName: ${self:app}-chat-${self:custom.stage}
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: username
                  AttributeType: S
                - AttributeName: userSortKey
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: userSortKeyIndex
                  KeySchema:
                      - AttributeName: userSortKey
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
                - IndexName: companyIdIndex
                  KeySchema:
                      - AttributeName: companyId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: username
                  KeyType: HASH
                - AttributeName: userSortKey
                  KeyType: RANGE
            TableName: ${self:app}-user-${self:custom.stage}
    CompanyTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: companyId
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: companyId
                  KeyType: HASH
            TableName: ${self:app}-company-${self:custom.stage}
