Resources:
    ChatTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: chatId
                  AttributeType: S
                - AttributeName: chatSortKey
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: chatId
                  KeyType: HASH
                - AttributeName: chatSortKey
                  KeyType: RANGE
            TableName: ${self:app}-chat-${self:custom.stage}
    # UserChatTable:
    #     Type: AWS::DynamoDB::Table
    #     Properties:
    #         AttributeDefinitions:
    #             - AttributeName: userChatId
    #               AttributeType: S
    #             - AttributeName: username
    #               AttributeType: S
    #             - AttributeName: chatId
    #               AttributeType: S
    #         BillingMode: PAY_PER_REQUEST
    #         GlobalSecondaryIndexes:
    #             - IndexName: usernameIndex
    #               KeySchema:
    #                   - AttributeName: username
    #                     KeyType: HASH
    #               Projection:
    #                   ProjectionType: ALL
    #             - IndexName: chatIdIndex
    #               KeySchema:
    #                   - AttributeName: username
    #                     KeyType: HASH
    #               Projection:
    #                   ProjectionType: ALL
    #         KeySchema:
    #             - AttributeName: userChatId
    #               KeyType: HASH
    #         TableName: ${self:app}-user-chat-${self:custom.stage}
    UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: username
                  AttributeType: S
                - AttributeName: companyId
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: companyIdIndex
                  KeySchema:
                      - AttributeName: companyId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: username
                  KeyType: HASH
            TableName: ${self:app}-user-${self:custom.stage}

    ConnectionTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: connectionId
                  AttributeType: S
                - AttributeName: username
                  AttributeType: S
                - AttributeName: companyId
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: companyIdIndex
                  KeySchema:
                      - AttributeName: companyId
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
                - IndexName: usernameIndex
                  KeySchema:
                      - AttributeName: username
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: connectionId
                  KeyType: HASH
            TableName: ${self:app}-connection-${self:custom.stage}
    LocationTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: locationId
                  AttributeType: S
                - AttributeName: username
                  AttributeType: S
                - AttributeName: timestamp
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: usernameIndex
                  KeySchema:
                      - AttributeName: username
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: locationId
                  KeyType: HASH
                - AttributeName: timestamp
                  KeyType: RANGE
            TableName: ${self:app}-location-${self:custom.stage}
    CompanyTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: companyId
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST

            KeySchema:
                - AttributeName: companyId
                  KeyType: HASH
            TableName: ${self:app}-company-${self:custom.stage}
