app: tcc
service: tcc-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false
  region: us-east-1
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-east-1:603366505042:table/connection
        - arn:aws:dynamodb:us-east-1:603366505042:table/user
        - arn:aws:dynamodb:us-east-1:603366505042:table/chat
    - Effect: Allow
      Action: dynamodb:Query
      Resource:
        - arn:aws:dynamodb:us-east-1:603366505042:table/user/index/*
        - arn:aws:dynamodb:us-east-1:603366505042:table/connection/index/*
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource:
        - arn:aws:lambda:us-east-1:603366505042:function:tcc-backend-dev-user
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminDeleteUser
      Resource: '*'
plugins:
  - aws-amplify-serverless-plugin
  - serverless-stack-output
custom:
  amplify:
    - filename: ../app/app/src/main/res/raw/awsconfiguration.json
      type: native
      appClient: CognitoUserPoolClient
    - filename: ../web/src/aws-exports.js
      type: javascript
      appClient: CognitoUserPoolClient
  output:
    file: ../web/src/stack.json
  apiUrl: !Join
    - ''
    - - 'https://'
      - !Ref ApiGatewayRestApi
      - '.execute-api.'
      - ${opt:region, self:provider.region}
      - '.amazonaws.com/'
      - ${opt:stage, self:provider.stage}
      - '/'

package:
  individually: true
  include:
    - '!*'
    - '!*/**'
functions:
  - ${file(functions/serverless.yml)}

resources:
  - ${file(dynamodb.yml)}
  - ${file(cognito.yml)}
  - ${file(outputs.yml)}
