app: tcc
service: tcc-backend

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    versionFunctions: false
    region: us-east-1
    websocketApiRouteSelectionExpression: $request.body.action

plugins:
    - serverless-stack-output
    - serverless-finch
    - aws-amplify-serverless-plugin

package:
    individually: true
    include:
        - '!*'
        - '!*/**'

custom:
    stage: ${opt:stage, self:provider.stage}
    amplify:
        - filename: ../app/app/src/main/res/raw/awsconfiguration.json
          type: native
          appClient: CognitoUserPoolClient

    client:
        bucketName: tcc-frontend
        distributionFolder: ../web/dist/web

    table: ${self:app}-table-${self:custom.stage}
    output:
        file: ../web/src/stack.json
    apiUrl: !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.'
          - ${opt:region, self:provider.region}
          - '.amazonaws.com/'
          - ${opt:stage, self:provider.stage}
          - '/'
    webSocketUrl: !Join
        - ''
        - - 'https://'
          - !Ref WebsocketsApi
          - '.execute-api.'
          - ${opt:region, self:provider.region}
          - '.amazonaws.com/'
          - ${opt:stage, self:provider.stage}
          - '/'

functions:
    - ${file(functions/serverless.yml)}

resources:
    - ${file(resources/roles.yml)}
    - ${file(resources/policies.yml)}
    - ${file(resources/dynamodb.yml)}
    - ${file(resources/cognito.yml)}
    - ${file(resources/cognito-identity-pool.yml)}
    - ${file(resources/outputs.yml)}
