app: tcc
service: tcc-backend

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    versionFunctions: false
    region: us-east-1
    websocketApiRouteSelectionExpression: $request.body.action
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
          Resource:
              - arn:aws:dynamodb:us-east-1:603366505042:table/${self:app}-table-${self:custom.stage}
        - Effect: Allow
          Action: dynamodb:Query
          Resource:
              - arn:aws:dynamodb:us-east-1:603366505042:table/${self:app}-table-${self:custom.stage}/index/*
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource:
              - arn:aws:lambda:us-east-1:603366505042:function:tcc-backend-dev-user
              - arn:aws:lambda:us-east-1:603366505042:function:tcc-backend-dev-ws-post-message

        - Effect: Allow
          Action:
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminSetUserPassword
              - cognito-idp:AdminDeleteUser
          Resource: '*'

plugins:
    - serverless-stack-output
    - aws-amplify-serverless-plugin
custom:
    stage: ${opt:stage, self:provider.stage}
    amplify:
        - filename: ../app/app/src/main/res/raw/awsconfiguration.json
          type: native
          appClient: CognitoUserPoolClient

    table: ${self:app}-table-${self:custom.stage}
    output:
        file: ../web/src/stack.json
    apiUrl: !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.'
          - ${opt:region, self:provider.region}
          - '.amazonaws.com/'
          - ${opt:stage, self:provider.stage}
          - '/'
    webSocketUrl: !Join
        - ''
        - - 'https://'
          - !Ref WebsocketsApi
          - '.execute-api.'
          - ${opt:region, self:provider.region}
          - '.amazonaws.com/'
          - ${opt:stage, self:provider.stage}
          - '/'
package:
    individually: true
    include:
        - '!*'
        - '!*/**'
functions:
    - ${file(functions/serverless.yml)}

resources:
    - ${file(dynamodb.yml)}
    - ${file(cognito.yml)}
    - ${file(cognito-identity-pool.yml)}
    - ${file(outputs.yml)}
