connection-handler:
  handler: functions/connection-handler/index.handler
  package:
    include:
      - functions/connection-handler/*
      - functions/connection-handler/*/**
  events:
    - websocket:
        route: $connect
        routeResponseSelectionExpression: $default
    - websocket:
        route: $disconnect
        routeResponseSelectionExpression: $default
  environment:
    API_TCC: ${self:custom.apiUrl}
send-message:
  handler: functions/send-message/index.handler
  package:
    include:
      - functions/send-message/*
      - functions/send-message/*/**
  events:
    - websocket:
        route: send-message
        routeResponseSelectionExpression: $default
user:
  handler: functions/user/index.handler
  package:
    include:
      - functions/user/*
      - functions/user/*/**
  events:
    - http:
        path: user
        method: GET
        cors: true
    - http:
        path: user/{userId}
        method: GET
        cors: true
    - websocket:
        route: post-user
        routeResponseSelectionExpression: $default
    - websocket:
        route: put-user
        routeResponseSelectionExpression: $default
    - websocket:
        route: delete-user
        routeResponseSelectionExpression: $default
  environment:
    API_URL: !Join
      - ''
      - - 'https://'
        - !Ref ApiGatewayRestApi
        - '.execute-api.'
        - ${opt:region, self:provider.region}
        - '.amazonaws.com/'
        - ${opt:stage, self:provider.stage}
