# REST handlers
user:
  handler: functions/user/index.handler
  package:
    include:
      - functions/user/*
      - functions/user/*/**
  events:
    - http:
        path: company/{companyId}/users
        method: GET
        cors: true
    - http:
        path: company/{companyId}/users/{userId}
        method: GET
        cors: true
    - http:
        path: company/{companyId}/users
        method: POST
        cors: true
    - http:
        path: company/{companyId}/users/{userId}
        method: PUT
        cors: true
    - http:
        path: company/{companyId}/users/{userId}
        method: DELETE
        cors: true
  environment:
    API_TCC: ${self:custom.apiUrl}

# Web Socket handlers
connection-handler:
  handler: functions/connection-handler/index.handler
  package:
    include:
      - functions/connection-handler/*
      - functions/connection-handler/*/**
  events:
    - websocket:
        route: $connect
        routeResponseSelectionExpression: $default
    - websocket:
        route: $disconnect
        routeResponseSelectionExpression: $default
  environment:
    API_TCC: ${self:custom.apiUrl}

send-message:
  handler: functions/send-message/index.handler
  package:
    include:
      - functions/send-message/*
      - functions/send-message/*/**
  events:
    - websocket:
        route: send-message
        routeResponseSelectionExpression: $default
