// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-09-13T18:45:48.655Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://2p8b6trvua.execute-api.us-east-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'us-east-1'
        }
    ],
    aws_cognito_identity_pool_id: 'us-east-1:37c2e9f4-7fac-4274-bd9e-747803cbbedb',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_qtIxjoqVD',
    aws_user_pools_web_client_id: '4ssv3lk591ehbtcspheg30n6ot'
};

export default awsmobile;
