// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.4.1 on 2020-08-23T02:22:02.525Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://qv7ica8p35.execute-api.us-east-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'us-east-1'
        }
    ],
    aws_cognito_identity_pool_id: 'us-east-1:73da1350-7766-4f17-b932-41fe4342d50f',
    aws_cognito_region: 'us-east-1',
    aws_project_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_1t5Hxze7t',
    aws_user_pools_web_client_id: '2tle8fpjvdrab07l8dtdi6o7h1'
};

export default awsmobile;
