const METHODS = {
    START_PUSH_TO_TALK: 'START_PUSH_TO_TALK',
    STOP_PUSH_TO_TALK: 'STOP_PUSH_TO_TALK',
};

const RESPONSE = {
    STARTED_PUSH_TO_TALK: 'STARTED_PUSH_TO_TALK',
    STOPPED_PUSH_TO_TALK: 'STOPPED_PUSH_TO_TALK',
    RECEIVED_PUSH_TO_TALK: 'RECEIVED_PUSH_TO_TALK',
};

module.exports = {
    METHODS,
    RESPONSE,
};
