Resources:
    TccTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: partitionKey
                  AttributeType: S
                - AttributeName: sortKey
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: sortKeyIndex
                  KeySchema:
                      - AttributeName: sortKey
                        KeyType: HASH
                      - AttributeName: partitionKey
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: partitionKey
                  KeyType: HASH
                - AttributeName: sortKey
                  KeyType: RANGE
            TableName: ${self:app}-table-${self:custom.stage}
